ProductBundle\Document\Product:
    repositoryClass: ProductBundle\Repository\ProductRepository
    fields:
        id:
            id:  true
        sid:
            type: integer
        productName:
            type: string
        category:
            type: string
        brand:
            type: string
        productMaterial:
            type: string
        imageUrl:
            type: string
        delivery:
            type: date
        details:
            type: string
        oldPrice:
            type: float
        newPrice:
            type: float
