product_homepage:
    path:     /create
    defaults: { _controller: ProductBundle:Default:create }

product_test:
    path:     /
    defaults: { _controller: ProductBundle:Default:index }

product_list:
    path:     /list
    defaults: { _controller: ProductBundle:Product:fetch }

rou_dispacher:
    path:     /dispath/{template}
    defaults: { _controller: ProductBundle:Default:dispatch }
    options:
        expose: true