product_home_page:
    path:     /
    defaults: { _controller: ProductBundle:Default:index }

product_list:
    path:     /list
    defaults: { _controller: ProductBundle:Product:fetch }


product_top:
    path:     /top
    defaults: { _controller: ProductBundle:Product:discount }

product_prodCat:
    path:     /cat
    defaults: { _controller: ProductBundle:Product:productsInCategory }

product_category:
    path:     /info
    defaults: { _controller: ProductBundle:Product:category }
