product_home_page:
    path:     /
    defaults: { _controller: ProductBundle:Default:index }

product_list:
    path:     /list
    defaults: { _controller: ProductBundle:Product:fetch }

product_order:
    path:     /order
    defaults: { _controller: ProductBundle:Product:order }

