product_homepage:
    path:     /create
    defaults: { _controller: ProductBundle:Default:create }

product_test:
    path:     /test
    defaults: { _controller: ProductBundle:Default:index }

product_list:
    path:     /list
    defaults: { _controller: ProductBundle:Product:fetch }

