services:
#    product.example:
#        class: ProductBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

     product.provider:
         class: ProductBundle\Services\provider
     
     product.provider_controller:
         class: ProductBundle\Controller\ProviderController